#!/usr/bin/php
<?php

	if (!defined( "APP_NAME" )) {
		define( "APP_NAME", 'apiport');
	}
	
	define('IS_DEBUG',1);

	$winbase = dirname(__FILE__)."/../../../classpath.php";
	require_once($winbase);
	
	define( "ROOT_APP_PATH", ROOT_TOP_PATH. "/apps/" . APP_NAME);
	define( "ROOT_PRO_PATH", ROOT_APP_PATH . "/phproot");
	define( "ROOT_BIN_PATH", ROOT_APP_PATH . "/binroot");

	$config = require(ROOT_PRO_PATH."/config/config.php");
	
	winBase::createConsole($config)->process();